from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class GameWidget(QWidget):
    def __init__(self, parent=None):
        super(GameWidget, self).__init__(parent)
        self.parent = parent
        self.buttons = [[QPushButton()]*3 for i in range(3)]

        self.player0Label = QLabel()
        self.player0Label.setObjectName("player0Label")
        self.player1Label = QLabel()
        self.player1Label.setObjectName("player1Label")
        self.statusLabel = QLabel()
        self.statusLabel.setObjectName("statusLabel")
        
        self.buttons[0][0] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[0][0].sizePolicy().hasHeightForWidth())
        self.buttons[0][0].setSizePolicy(sizePolicy)
        self.buttons[0][0].setObjectName("buttons[0][0]")

        self.buttons[0][1] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[0][1].sizePolicy().hasHeightForWidth())
        self.buttons[0][1].setSizePolicy(sizePolicy)
        self.buttons[0][1].setObjectName("buttons[0][1]")
        
        self.buttons[0][2] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[0][2].sizePolicy().hasHeightForWidth())
        self.buttons[0][2].setSizePolicy(sizePolicy)
        self.buttons[0][2].setObjectName("buttons[0][2]")

        self.buttons[1][0] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[1][0].sizePolicy().hasHeightForWidth())
        self.buttons[1][0].setSizePolicy(sizePolicy)
        self.buttons[1][0].setObjectName("buttons[1][0]")

        self.buttons[1][1] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[1][1].sizePolicy().hasHeightForWidth())
        self.buttons[1][1].setSizePolicy(sizePolicy)
        self.buttons[1][1].setObjectName("buttons[1][1]")
        
        self.buttons[1][2] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[1][2].sizePolicy().hasHeightForWidth())
        self.buttons[1][2].setSizePolicy(sizePolicy)
        self.buttons[1][2].setObjectName("buttons[1][2]")
        
        self.buttons[2][0] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[2][0].sizePolicy().hasHeightForWidth())
        self.buttons[2][0].setSizePolicy(sizePolicy)
        self.buttons[2][0].setObjectName("buttons[2][0]")

        self.buttons[2][1] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[2][1].sizePolicy().hasHeightForWidth())
        self.buttons[2][1].setSizePolicy(sizePolicy)
        self.buttons[2][1].setObjectName("buttons[2][1]")
        
        self.buttons[2][2] = QPushButton()
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons[2][2].sizePolicy().hasHeightForWidth())
        self.buttons[2][2].setSizePolicy(sizePolicy)
        self.buttons[2][2].setObjectName("buttons[2][2]")
        
        self.line = QFrame()
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QFrame()
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        
        self.line_3 = QFrame()
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.line_4 = QFrame()
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.line_5 = QFrame()
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.line_6 = QFrame()
        self.line_6.setFrameShape(QFrame.VLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.line_7 = QFrame()
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        
        self.line_8 = QFrame()
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_5.addWidget(self.player0Label, 0, Qt.AlignHCenter|Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.player1Label, 0, Qt.AlignHCenter|Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.statusLabel, 0, Qt.AlignHCenter|Qt.AlignTop)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_4.addWidget(self.buttons[0][0])
        self.horizontalLayout_4.addWidget(self.line)
        self.horizontalLayout_4.addWidget(self.buttons[0][1])
        self.horizontalLayout_4.addWidget(self.line_6)
        self.horizontalLayout_4.addWidget(self.buttons[0][2])

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.addWidget(self.buttons[1][0])
        self.horizontalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_2.addWidget(self.buttons[1][1])
        self.horizontalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_2.addWidget(self.buttons[1][2])
        
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.addWidget(self.buttons[2][0])
        self.horizontalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_3.addWidget(self.buttons[2][1])
        self.horizontalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_3.addWidget(self.buttons[2][2])

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.line_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.line_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi()
        self.setLayout(self.verticalLayout)

    def retranslateUi(self, ):
        self.player0Label.setText("Player X: nick")
        self.player1Label.setText("Player O: nick")
        self.statusLabel.setText("Status")
        #self.buttons[0][0].setIcon(QIcon('tic-tac-toe-O.png'))
        self.buttons[0][0].setIconSize(QSize(80,80))
        self.buttons[0][1].setIconSize(QSize(80,80))
        self.buttons[0][2].setIconSize(QSize(80,80))
        self.buttons[1][0].setIconSize(QSize(80,80))
        self.buttons[1][1].setIconSize(QSize(80,80))
        self.buttons[1][2].setIconSize(QSize(80,80))
        self.buttons[2][0].setIconSize(QSize(80,80))
        self.buttons[2][1].setIconSize(QSize(80,80))
        self.buttons[2][2].setIconSize(QSize(80,80))
        
        self.buttons[0][0].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[0][0].setStyleSheet("border: 0")
        self.buttons[0][1].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[0][1].setStyleSheet("border: 0")
        self.buttons[0][2].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[0][2].setStyleSheet("border: 0")
        self.buttons[1][0].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[1][0].setStyleSheet("border: 0")
        self.buttons[1][1].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[1][1].setStyleSheet("border: 0")
        self.buttons[1][2].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[1][2].setStyleSheet("border: 0")
        self.buttons[2][0].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[2][0].setStyleSheet("border: 0")
        self.buttons[2][1].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[2][1].setStyleSheet("border: 0")
        self.buttons[2][2].setStyleSheet("background-color: rgb(240,240,240)")
        self.buttons[2][2].setStyleSheet("border: 0")

        self.line.setStyleSheet("background-color: black")
        self.line_2.setStyleSheet("background-color: black")
        self.line_3.setStyleSheet("background-color: black")
        self.line_4.setStyleSheet("background-color: black")
        self.line_5.setStyleSheet("background-color: black")
        self.line_6.setStyleSheet("background-color: black")
        self.line_7.setStyleSheet("background-color: black")
        self.line_8.setStyleSheet("background-color: black")